name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install `mdbook`
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest

      - run: mdbook build
      - run: mdbook test

      - name: Publish to `gh-pages`
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
